Chamilo\CmsBundle\Document\Page:
    uri_schema: /page/{title}
    token_providers:
        title: [content_method, { method: getTitle }]

Chamilo\CmsBundle\Document\Post:
    uri_schema: /post/{date}/{title}
    token_providers:
        date: [content_datetime, { method: getDate }]
        title: [content_method, { method: getTitle }]
